# GHA workflow

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:
defaults:
    run:
        shell: bash

jobs:
    tests:
        name: "code quality control"
        runs-on: "ubuntu-latest"
        steps:
            - name: "prepare"
              uses: "actions/checkout@v2"
            - name: "python setup"
              uses: "actions/setup-python@v4"
              with:
                python-version: "3.8"
            - name: "linting dependencies"
              run: |
                    python -m pip install -r requirements-test.txt

            - name: "check linting"
              continue-on-error: true
              id: tox_status
              run: |
                cd calibration_tool
                python -m tox -e lint
            - name: "result"
              if: always()
              run: |
                if ${{ steps.tox_status.outcome != 'success' }}; then
                    echo "Pylint=Failed" >> $GITHUB_ENV
                    echo "Pylint_Color=red" >> $GITHUB_ENV
                    exit 1
                else
                    echo "Pylint=Passed" >> $GITHUB_ENV
                    echo "Pylint_Color=green" >> $GITHUB_ENV
                fi
            - name: Create Pylint Badge
              if: always()
              uses: schneegans/dynamic-badges-action@v1.6.0
              with:
                auth: ${{ secrets.GIST_SECRET }}
                gistID: a9924565e021b9c897e7e89e3ea4163b
                filename: pycalibration_tool_linting.json
                label: Pylint
                message: ${{ env.Pylint }}
                color: ${{ env.Pylint_Color }}

